services:
  postgresdb:
    image: postgres:latest
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"

    ports:
      - 5432:5432
    volumes:
      - psql:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: dockerfile
    depends_on:
      - postgresdb
    env_file:
      - .env
    ports:
      - 3000:3000

volumes:
  psql: